#!/bin/sh
echo "Migrating classess... "
retval=`php extra/shell/MigrateCheckout.php; echo $?`
if [ $retval -ne 0 ]; then
        echo "Migration failed, try to manually run extra/shell/MigrateCheckout.php\n"
        exit;
fi
echo "Done.\n"
