#!/bin/sh
echo "Migrating classes... "
retval=`php extra/shell/MigrateCommit.php; echo $?`
if [ $retval -ne 0 ]; then
        echo "Migration failed.";
        exit $retval;
fi
git add extra/classes/
git add extra/fieldcollections/
echo "Done.\n"
